<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_pathfill64728cHR Administration</name>
   <tag></tag>
   <elementGuidId>2e6adf10-10f7-4e89-90fe-697e5738f079</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu_item_101</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_item_101']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;HR Administration&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5f39edf4-7a17-4c59-a41d-a4a4a32b951d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>menu_admin_viewSystemUsers</value>
      <webElementGuid>228a087c-537f-41f8-a649-892a5b37c11b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/admin/systemUsers</value>
      <webElementGuid>2f3cde3c-2782-4d50-9b48-6bc60fc5c12a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ui-sref</name>
      <type>Main</type>
      <value>admin.systemUsers</value>
      <webElementGuid>e007a33a-ddba-4335-8090-f7a4960a1583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ui-sref-opts</name>
      <type>Main</type>
      <value>{reload: true, notify: true}</value>
      <webElementGuid>3695edb5-375c-456f-8ff1-49445dcc63c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-target</name>
      <type>Main</type>
      <value>{{undefined}}</value>
      <webElementGuid>704f63ea-94cc-4934-80f9-ceda16e71b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu_item_101</value>
      <webElementGuid>fc1b1c10-d458-427e-a004-82785efc32b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> main-menu-item-1</value>
      <webElementGuid>279c5cb8-e1ed-4848-b69d-e84370de08d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip</name>
      <type>Main</type>
      <value>HR Administration</value>
      <webElementGuid>d65ef91e-da7a-4655-af3c-bf7bfaeba89b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-position</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>e2916e4c-79d7-41d5-a4e0-87d2b2ea4210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'hidden': !vm.showMenu}</value>
      <webElementGuid>cd298a45-6713-4f88-b0d3-c5055f9a5263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>path{fill:#64728c;}
HR Administration</value>
      <webElementGuid>6be05c8b-429e-481c-9fba-af335d1a14a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;left_menu_item_10&quot;)/a[@id=&quot;menu_item_101&quot;]</value>
      <webElementGuid>3cee9334-4d50-41d1-8e4f-2354805ee6a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu_item_101']</value>
      <webElementGuid>0e2ef61e-c93c-4584-a927-71f4e5d72a8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='left_menu_item_10']/a</value>
      <webElementGuid>fbd1b134-a9fe-4291-9acb-531db65b941f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='People Management'])[1]/following::a[1]</value>
      <webElementGuid>be5a0d18-9b8a-4030-9d80-26c019cbf550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='search'])[1]/following::a[1]</value>
      <webElementGuid>e34b877c-e5fb-43d8-aede-5809ecea367b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HR Administration'])[2]/preceding::a[1]</value>
      <webElementGuid>35bf08c0-d563-43db-a4c8-15db73b550e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/admin/systemUsers')]</value>
      <webElementGuid>981680c3-6b45-4342-af27-3ce126ec8d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>813faad9-78ed-429c-8c61-475b27a20b14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/admin/systemUsers' and @id = 'menu_item_101' and (text() = 'path{fill:#64728c;}
HR Administration' or . = 'path{fill:#64728c;}
HR Administration')]</value>
      <webElementGuid>1c7bb46a-b7b1-4463-9f47-5ff59187e550</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
