<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Work Schedules (1)</name>
   <tag></tag>
   <elementGuidId>25c238dc-2b9e-4f92-916f-1d79875b4c38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='top-ribbon-menu']/div[3]/top-level-menu-item[2]/div/sub-menu-container/div/div[4]/sub-menu-container/div/div[8]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Work Schedules&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1a93043b-d1b8-4d07-9072-5394dad20d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!menu.children &amp;&amp; !!menu.uiSref &amp;&amp; maxLevels &lt;= 0</value>
      <webElementGuid>1772a49e-45f4-40ef-a15a-f0ad899d7319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sub-menu-item-link truncate</value>
      <webElementGuid>f5ff8de2-a7c6-4ccb-a97d-499694972f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ui-sref</name>
      <type>Main</type>
      <value>vuepim.work_schedules</value>
      <webElementGuid>9f9eda75-8301-4227-858c-fe2270fe063c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ui-sref-active</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>214cb523-89a3-42d0-b720-72dc30433377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-target</name>
      <type>Main</type>
      <value>{{menu.target}}</value>
      <webElementGuid>3e4d540c-ca45-47d8-8181-6ff13a335961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>more_menu_child_menu_pim_pimWorkSchedules</value>
      <webElementGuid>c3933704-66c5-4a86-a098-99b1966092e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2bf206b2-b99b-4b97-9e3f-b46b79ab9b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/pim/work_schedules</value>
      <webElementGuid>eea3321b-a5f7-42f8-b320-1f9ff722e198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Work Schedules</value>
      <webElementGuid>30d9421f-e5ff-48e6-990b-5b18654ac94a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-ribbon-menu&quot;)/div[@class=&quot;top-ribbon-menu-more-items&quot;]/top-level-menu-item[2]/div[@class=&quot;top-level-menu-item-container&quot;]/sub-menu-container[@class=&quot;level-1-sub-menu opened&quot;]/div[@class=&quot;sub-menu-container&quot;]/div[@class=&quot;sub-menu-item&quot;]/sub-menu-container[@class=&quot;direction-left opened&quot;]/div[@class=&quot;sub-menu-container&quot;]/div[@class=&quot;sub-menu-item&quot;]/a[@class=&quot;sub-menu-item-link truncate&quot;]</value>
      <webElementGuid>da337543-9da7-436b-ad5a-fd70e375f47c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top-ribbon-menu']/div[3]/top-level-menu-item[2]/div/sub-menu-container/div/div[4]/sub-menu-container/div/div[8]/a</value>
      <webElementGuid>5c6d2ee9-b183-4b61-9cae-875ba094dade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Work Schedules')])[2]</value>
      <webElementGuid>bad19899-f1bd-4966-bc4f-6eb5b7579637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Templates'])[3]/following::a[1]</value>
      <webElementGuid>612f6624-f831-4ca1-92d0-d1893766896c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Directory Configuration'])[2]/following::a[2]</value>
      <webElementGuid>e31d99c5-3931-4679-9e1f-21fbbf9b6f62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job and Salary Events'])[2]/preceding::a[1]</value>
      <webElementGuid>00bcd062-506d-4ec1-b15c-a8b2cad9a178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nationalities'])[2]/preceding::a[2]</value>
      <webElementGuid>efda8f02-a8d3-4a2e-a007-67991140dca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#/pim/work_schedules')])[2]</value>
      <webElementGuid>91a84856-7938-4859-b183-add2b38f59f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/sub-menu-container/div/div[8]/a</value>
      <webElementGuid>0eb2d239-cd31-407f-99cc-572136dcce3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/pim/work_schedules' and (text() = 'Work Schedules' or . = 'Work Schedules')]</value>
      <webElementGuid>653f24d0-6366-4a8d-8973-f62e84117d31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
