<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_more_vert</name>
   <tag></tag>
   <elementGuidId>093c4b89-5daf-41c7-b6e8-aa2dd889d206</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.expand-icon.material-icons</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='top-ribbon-menu']/div[3]/top-level-menu-item/div/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;More more_vert&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>7b5dcd0a-9610-4150-a387-6fdf39147086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>children &amp;&amp; expandIcon</value>
      <webElementGuid>e850320c-70dc-4185-9190-06e4bad8a4db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>expand-icon material-icons</value>
      <webElementGuid>9e99964f-93ea-4aa0-b91e-bd4e4efb3f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>more_vert</value>
      <webElementGuid>b7c9ff90-f9c7-45b4-9017-f45db4fcc6c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-ribbon-menu&quot;)/div[@class=&quot;top-ribbon-menu-more-items&quot;]/top-level-menu-item[1]/div[@class=&quot;top-level-menu-item-container&quot;]/a[@class=&quot;top-level-menu-item&quot;]/i[@class=&quot;expand-icon material-icons&quot;]</value>
      <webElementGuid>f8b82caf-cacc-4103-8c93-b01331788139</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top-ribbon-menu']/div[3]/top-level-menu-item/div/a/i</value>
      <webElementGuid>7c134436-8f71-4f92-a5b3-b780c6f7b935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Candidate Records'])[1]/following::i[1]</value>
      <webElementGuid>f3d6fb6e-8bb8-4238-b9b7-2f25ad15224f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='oxd_menu_left'])[1]/preceding::i[1]</value>
      <webElementGuid>cb22fd2f-d88e-4819-aa77-099b31e9ba70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='more_vert']/parent::*</value>
      <webElementGuid>e5e4a309-5ef2-417f-91db-018ff85b6be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//top-level-menu-item/div/a/i</value>
      <webElementGuid>c4a873b0-af21-48da-9518-65c5633b4f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'more_vert' or . = 'more_vert')]</value>
      <webElementGuid>8eff86f4-0368-4df6-9bfa-772e6191aeab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
