<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Job Description</name>
   <tag></tag>
   <elementGuidId>bb0299e3-67e2-4aeb-ad0e-26e65b8fdb6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.form-group.col-12</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-holder']/div/div/div/div[2]/form/oxd-decorator/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>form[name=&quot;oxdModalForm&quot;] div >> internal:has-text=&quot;Job Description&quot;i >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>58ee69ca-93e2-4fcd-8bba-13da26d61c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-group col-12</value>
      <webElementGuid>15f2ce14-916e-46ff-a48f-f8c416199438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-repeat</name>
      <type>Main</type>
      <value>item in form.items</value>
      <webElementGuid>24af85f5-9a5e-437c-bbd6-81c1996255d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>form</name>
      <type>Main</type>
      <value>item</value>
      <webElementGuid>63bc7a55-3e48-48a7-8e90-2bdeacd4f638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Job Description </value>
      <webElementGuid>5f5a6abd-8452-43d0-a90b-ca7d9f6e4a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-holder&quot;)/div[@class=&quot;modal show&quot;]/div[@class=&quot;modal-dialog modal-md&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/form[@class=&quot;generic-oxd-modal-form needs-validation ng-valid-duplication-job-title ng-valid-file-size ng-valid-file-type ng-dirty ng-invalid ng-invalid-tv4-302 ng-valid-parse ng-invalid-schema-form&quot;]/oxd-decorator[1]/div[@class=&quot;form-row&quot;]/div[@class=&quot;form-group col-12&quot;]</value>
      <webElementGuid>0baacffb-81ae-41ef-bbc7-8dd50a914387</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-holder']/div/div/div/div[2]/form/oxd-decorator/div/div[2]</value>
      <webElementGuid>ea4ae06b-0b07-4c3a-b5a2-c50ec97200db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Required'])[1]/following::div[1]</value>
      <webElementGuid>ca878658-6ed8-4268-a688-578cc56ee323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::div[2]</value>
      <webElementGuid>6cd1e030-d202-4eab-b869-f53aa3bdfe68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job Specification'])[1]/preceding::div[2]</value>
      <webElementGuid>a85a897a-93b0-4e15-8ef0-28b03bfda598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//oxd-decorator/div/div[2]</value>
      <webElementGuid>4933ffe5-ba94-4be3-a4a2-122ca6733389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@form = 'item' and (text() = ' Job Description ' or . = ' Job Description ')]</value>
      <webElementGuid>fa081d9e-afc5-4a0e-a8f5-26cef81e8588</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
