<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__select-dropdown active</name>
   <tag></tag>
   <elementGuidId>9b52a2bf-6b14-4305-bb3f-3d16ab508e27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.select-dropdown.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='50']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#jobTitlesDiv >> internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>de4b857e-2b0b-4c56-8212-ede4417d01c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ef7be77c-a57f-4223-a8cc-23a843fc2469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-dropdown active</value>
      <webElementGuid>01b3226c-8b30-45b2-ade2-95b4f223cfc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1cbf4298-6c15-40f4-854c-9b349126ca28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-activates</name>
      <type>Main</type>
      <value>select-options-64359a49-6b3d-9475-e8b1-03042e85bdf4</value>
      <webElementGuid>347a8bee-8101-4ac9-bcce-fca924c5c342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>4095cf9e-e96a-4d5b-8a70-577455940d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobTitlesDiv&quot;)/crud-panel[1]/div[@class=&quot;form-div&quot;]/div[@class=&quot;list-container&quot;]/list[1]/ul[@class=&quot;pagination&quot;]/li[@class=&quot;page-size&quot;]/div[@class=&quot;select-wrapper&quot;]/input[@class=&quot;select-dropdown active&quot;]</value>
      <webElementGuid>8719fd61-4052-4c51-97c3-ded4f2822f4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='50']</value>
      <webElementGuid>804de7c8-96d1-4404-be07-ee390047e14e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jobTitlesDiv']/crud-panel/div/div/list/ul/li[2]/div/input</value>
      <webElementGuid>cf0aa42f-56ba-476b-a510-636d2c224135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/input</value>
      <webElementGuid>1a93ea70-c61b-4cd1-a302-7567e48ee95c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>5bfb5cae-4bbf-481a-bdfd-fb9af6734705</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
