<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label</name>
   <tag></tag>
   <elementGuidId>af2882f9-3663-4915-86b1-a4fbc1d0f686</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) > td > label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jobTitlesDiv']/crud-panel/div/div/list/table/tbody/tr[2]/td/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Art Director ohrm_edit&quot;i] >> label</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e6389f30-f6fb-458b-9091-791ae4a27a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>checkbox_list0_17</value>
      <webElementGuid>3d7efb8d-780a-4d76-988f-3886d724c510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobTitlesDiv&quot;)/crud-panel[1]/div[@class=&quot;form-div&quot;]/div[@class=&quot;list-container&quot;]/list[1]/table[@class=&quot;highlight bordered&quot;]/tbody[1]/tr[2]/td[1]/label[1]</value>
      <webElementGuid>3b96484b-3e39-4bd6-806b-0cca233f0d79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jobTitlesDiv']/crud-panel/div/div/list/table/tbody/tr[2]/td/label</value>
      <webElementGuid>ae5daa13-3f19-4691-ab88-6c60c05d8556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/label</value>
      <webElementGuid>419c26c5-e484-4dd3-a7dd-804dfdb784eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jobTitlesDiv']/crud-panel/div/div/list/table/tbody/tr/td/label</value>
      <webElementGuid>30ec821a-d574-4d0d-a74d-aa395741fdca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>5d65f8e1-c75a-4ed7-96c7-72a4113eeb29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jobTitlesDiv']/crud-panel/div/div/list/table/tbody/tr[7]/td/label</value>
      <webElementGuid>4e7b4cb3-04ff-4342-bf8a-c4e3e46db58c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td/label</value>
      <webElementGuid>7e6b9e54-03e7-4fa9-8cd4-d40104441100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jobTitlesDiv']/crud-panel/div/div/list/table/tbody/tr[6]/td/label</value>
      <webElementGuid>b9013908-57c0-4ab1-8dd7-83b3a49156d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/label</value>
      <webElementGuid>f97156ff-62d0-48e7-87bc-b1194184a011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jobTitlesDiv']/crud-panel/div/div/list/table/tbody/tr[5]/td/label</value>
      <webElementGuid>80b2e572-3916-4620-99d5-7a0cb7c0924c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/label</value>
      <webElementGuid>e00a0ab3-b783-4fd4-bc1e-b266e11f3489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jobTitlesDiv']/crud-panel/div/div/list/table/tbody/tr[4]/td/label</value>
      <webElementGuid>431a42fa-9802-42a5-9475-5cf531f6e06d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/label</value>
      <webElementGuid>b335696e-e45e-48e3-9984-4a2bac84d322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jobTitlesDiv']/crud-panel/div/div/list/table/tbody/tr[3]/td/label</value>
      <webElementGuid>eb5ce624-367e-481d-8d57-666d5fb5f1e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/label</value>
      <webElementGuid>61e3aedc-20ef-4000-aa2e-d0e14c282045</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
