<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Required</name>
   <tag></tag>
   <elementGuidId>0d59df60-96d8-433d-81ea-cc77bf06a9df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.invalid-feedback</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-holder']/div/div/div/div[2]/form/oxd-decorator/div/div/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Required&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9f09a13c-5de5-425a-aae1-3b50a7cb3139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>invalid-feedback</value>
      <webElementGuid>12fadae2-f040-44bf-8930-ad1e0d920e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sf-message</name>
      <type>Main</type>
      <value>form.description</value>
      <webElementGuid>df23207b-9e21-4c48-aead-9e67c096540d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Required</value>
      <webElementGuid>420bb147-8266-46f9-821f-f705a4a100b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-holder&quot;)/div[@class=&quot;modal show&quot;]/div[@class=&quot;modal-dialog modal-md&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/form[@class=&quot;generic-oxd-modal-form needs-validation ng-valid-duplication-job-title ng-valid-file-size ng-valid-file-type ng-dirty ng-invalid ng-invalid-tv4-302 ng-valid-parse ng-invalid-schema-form&quot;]/oxd-decorator[1]/div[@class=&quot;form-row&quot;]/div[@class=&quot;form-group col-6&quot;]/div[@class=&quot;text-input-field-container&quot;]/span[@class=&quot;invalid-feedback&quot;]</value>
      <webElementGuid>16dfa1a2-7109-474f-8cbd-05cce5786408</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-holder']/div/div/div/div[2]/form/oxd-decorator/div/div/div[2]/span</value>
      <webElementGuid>9cdc339b-156f-4b9f-88c1-339fca014cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::span[1]</value>
      <webElementGuid>83b6ea15-5652-4e94-94aa-344241f95616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job Description'])[2]/preceding::span[1]</value>
      <webElementGuid>e01536d4-3a05-4184-b628-e22a2a63e2e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job Specification'])[1]/preceding::span[2]</value>
      <webElementGuid>929efe2a-0c62-414d-bf46-b87486052088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Required']/parent::*</value>
      <webElementGuid>2829ffb6-e27e-4c3a-b3b2-3741ddc4d7f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/span</value>
      <webElementGuid>56ff4acb-a21a-4c98-8f8b-e46891b87e03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Required' or . = 'Required')]</value>
      <webElementGuid>c0803bc0-0cca-4974-9b86-7cd47b4ca86d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
