<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_14354675878</name>
   <tag></tag>
   <elementGuidId>33ed2747-158b-4fd6-ad3e-82eb7adf628f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ng-include > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jobTitlesDiv']/crud-panel/div/div/list/table/tbody/tr/td[2]/ng-include/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;14354675878$$$$$&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>58eaf0ec-2acd-4fae-aad8-de57468466e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>14354675878$$$$$</value>
      <webElementGuid>62b6c449-bdf7-48b1-aa57-159de5ecd556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobTitlesDiv&quot;)/crud-panel[1]/div[@class=&quot;form-div&quot;]/div[@class=&quot;list-container&quot;]/list[1]/table[@class=&quot;highlight bordered&quot;]/tbody[1]/tr[1]/td[@class=&quot;cursor-pointer&quot;]/ng-include[1]/span[1]</value>
      <webElementGuid>12e107dc-6430-4e4e-92f3-c588dce72a12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jobTitlesDiv']/crud-panel/div/div/list/table/tbody/tr/td[2]/ng-include/span</value>
      <webElementGuid>dda42f69-456a-43fe-a0f2-8b055f590cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job Description'])[1]/following::span[1]</value>
      <webElementGuid>4a22fbdd-4b53-42d1-9aa5-69c0992f13ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_upward'])[1]/following::span[2]</value>
      <webElementGuid>7a6b1f0d-fa27-4adc-93ec-9c3efcecfee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='software dev'])[1]/preceding::span[1]</value>
      <webElementGuid>bfa26b17-91e6-4253-a70d-b3b0bbf54d83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ohrm_edit'])[1]/preceding::span[2]</value>
      <webElementGuid>3c0ac0c9-709e-4c33-a661-7ae09ce98877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='14354675878$$$$$']/parent::*</value>
      <webElementGuid>c0c18c4a-45ff-4617-b3f5-9a0a9113491d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-include/span</value>
      <webElementGuid>e5fd364c-1482-447f-b4cf-61240247459b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '14354675878$$$$$' or . = '14354675878$$$$$')]</value>
      <webElementGuid>da32ba9b-e929-49a0-aabf-d3e9d6cc27ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
