<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_BA</name>
   <tag></tag>
   <elementGuidId>114d147d-5d86-48b2-8259-9b2ecdc41cc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jobTitlesDiv']/crud-panel/div/div/list/table/tbody/tr/td[2]/ng-include/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ng-include > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;BA&quot;i >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e6af6882-5ea3-4096-9e71-a75934c65e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BA</value>
      <webElementGuid>29f277e5-84f0-48a5-b521-2fb9dc3f7065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobTitlesDiv&quot;)/crud-panel[1]/div[@class=&quot;form-div&quot;]/div[@class=&quot;list-container&quot;]/list[1]/table[@class=&quot;highlight bordered&quot;]/tbody[1]/tr[@class=&quot;grey lighten-5&quot;]/td[@class=&quot;cursor-pointer&quot;]/ng-include[1]/span[1]</value>
      <webElementGuid>0c92717c-7924-4826-83e8-47184266bce9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jobTitlesDiv']/crud-panel/div/div/list/table/tbody/tr/td[2]/ng-include/span</value>
      <webElementGuid>a2a1018e-faab-4cb7-bbd6-e61c1576b2ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job Description'])[1]/following::span[1]</value>
      <webElementGuid>8da7945b-5804-40f1-97a9-5ee8462c5db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_upward'])[1]/following::span[2]</value>
      <webElementGuid>9157d871-a7b7-4d8b-be74-dc1b21a6c330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BA'])[2]/preceding::span[1]</value>
      <webElementGuid>545f75bb-0444-4e3c-b28f-11c6eba95e23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ohrm_edit'])[1]/preceding::span[2]</value>
      <webElementGuid>d4a987b7-6e8b-4c66-abe0-83504043a255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BA']/parent::*</value>
      <webElementGuid>431ea815-0062-4788-8d6d-6972d7cd0123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-include/span</value>
      <webElementGuid>dd24f148-887d-4f6e-8e61-97218c20b7c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'BA' or . = 'BA')]</value>
      <webElementGuid>1371d00f-eb77-4b4a-96aa-11918ed6c12a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
