<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_eCVV920445356785</name>
   <tag></tag>
   <elementGuidId>7bfaad83-b0e5-4c58-931e-2b21952d571f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(24) > td[name=&quot;listField.name&quot;] > ng-include > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jobTitlesDiv']/crud-panel/div/div/list/table/tbody/tr[24]/td[2]/ng-include/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;eCVV920445356785&amp;&amp;#&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>173cccac-7e48-4e33-9ee9-b12d0587bf50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>eCVV920445356785&amp;&amp;#</value>
      <webElementGuid>3cde0681-072c-4b85-a87c-bbc1c21a095c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobTitlesDiv&quot;)/crud-panel[1]/div[@class=&quot;form-div&quot;]/div[@class=&quot;list-container&quot;]/list[1]/table[@class=&quot;highlight bordered&quot;]/tbody[1]/tr[24]/td[@class=&quot;cursor-pointer&quot;]/ng-include[1]/span[1]</value>
      <webElementGuid>197e5082-0e51-4cac-8382-6e48c4c7ca51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jobTitlesDiv']/crud-panel/div/div/list/table/tbody/tr[24]/td[2]/ng-include/span</value>
      <webElementGuid>a119038e-b104-4aa8-b1b8-c98dd76acbf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ohrm_edit'])[23]/following::span[1]</value>
      <webElementGuid>f27cb3f1-769c-4fea-a118-1b990c17820f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Digital Marketing Manager'])[1]/following::span[2]</value>
      <webElementGuid>1ac0cc70-ea36-41c3-8736-9cf04dc8868d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Responsible for developing software requirements'])[1]/preceding::span[1]</value>
      <webElementGuid>66e99056-cbe4-48b9-929b-08bc82edbfb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ohrm_edit'])[24]/preceding::span[2]</value>
      <webElementGuid>bdd24a21-57fc-4e51-844b-57a039422776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='eCVV920445356785&amp;&amp;#']/parent::*</value>
      <webElementGuid>cdc87424-5283-4f15-ada3-44b2ebd155c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[24]/td[2]/ng-include/span</value>
      <webElementGuid>40aebf6b-17dc-4ebe-9d43-5fb60179cc58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'eCVV920445356785&amp;&amp;#' or . = 'eCVV920445356785&amp;&amp;#')]</value>
      <webElementGuid>004f6007-acb7-4340-be05-fe8b9874b9d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
