<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_more_horizSelect All</name>
   <tag></tag>
   <elementGuidId>db0fb9a2-c551-4b2f-accc-000303ae9305</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th.list-options</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jobTitlesDiv']/crud-panel/div/div/list/table/thead/tr/th</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;more_horiz&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>467b2d47-4862-4339-8a0c-1f4df468e62e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-options</value>
      <webElementGuid>d4ac9fd2-b4fd-42cb-a297-e00979623378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field</name>
      <type>Main</type>
      <value>id</value>
      <webElementGuid>b580f7f1-46d4-4cc8-8feb-d1a39c4f1291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>listData.selectable &amp;&amp; (list.hasPermissions(listData.listActions) || listData.configurable)</value>
      <webElementGuid>06fee47f-99a7-4ba2-a173-5bc4c44aa8dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>more_horizSelect All</value>
      <webElementGuid>1478bb27-ae89-437e-94b8-b97d110212c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobTitlesDiv&quot;)/crud-panel[1]/div[@class=&quot;form-div&quot;]/div[@class=&quot;list-container&quot;]/list[1]/table[@class=&quot;highlight bordered&quot;]/thead[1]/tr[1]/th[@class=&quot;list-options&quot;]</value>
      <webElementGuid>55544409-02a2-4430-93d7-cde87b6c8d7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jobTitlesDiv']/crud-panel/div/div/list/table/thead/tr/th</value>
      <webElementGuid>5b22e4c5-d176-4815-9d15-ef752e2424db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Timesheet'])[2]/following::th[1]</value>
      <webElementGuid>0cc5ed15-7ac1-4467-a4d0-ccdd13bc0fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit Request'])[2]/following::th[1]</value>
      <webElementGuid>923397c7-8241-4afc-af05-e9bb494bc019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th</value>
      <webElementGuid>c924b121-26b8-4edd-aeb5-ea01b4affc38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'more_horizSelect All' or . = 'more_horizSelect All')]</value>
      <webElementGuid>ad8f76ef-a643-4766-ad41-c645a95a70c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
