<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_pathfill64728cHR Administration</name>
   <tag></tag>
   <elementGuidId>041dd1b9-6b2f-4fc7-a421-1a6530a5c901</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu_item_101</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_item_101']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;HR Administration&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3fd41474-ed56-403d-939d-8c577f3c95c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>menu_admin_viewSystemUsers</value>
      <webElementGuid>a6038b84-1865-4451-95e5-e65a15514ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/admin/systemUsers</value>
      <webElementGuid>aae1722c-2bf8-4eb4-a592-a66d4e126c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ui-sref</name>
      <type>Main</type>
      <value>admin.systemUsers</value>
      <webElementGuid>9267ff26-80ab-4a1d-8dbc-bd9fe0d7d11c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ui-sref-opts</name>
      <type>Main</type>
      <value>{reload: true, notify: true}</value>
      <webElementGuid>03a626d6-e158-48f2-b9b1-0c0fc0fa0b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-target</name>
      <type>Main</type>
      <value>{{undefined}}</value>
      <webElementGuid>399f1b89-cde3-4b12-9019-37055c6bc640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu_item_101</value>
      <webElementGuid>601f6d9f-a1b1-4f83-9008-0a61fc2ba27c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> main-menu-item-1</value>
      <webElementGuid>bf88d825-5cb5-4676-946a-bf26fefea907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip</name>
      <type>Main</type>
      <value>HR Administration</value>
      <webElementGuid>ee96bdd9-0176-45ce-a01a-8438cee119c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-position</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>30e4ce93-6a81-487e-80d8-ecf929dbc80d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'hidden': !vm.showMenu}</value>
      <webElementGuid>2fc1c0dd-8b62-4f31-ba4d-663e3f08458b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>path{fill:#64728c;}
HR Administration</value>
      <webElementGuid>0a6ed583-e592-44b9-8808-920444682549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;left_menu_item_10&quot;)/a[@id=&quot;menu_item_101&quot;]</value>
      <webElementGuid>54239ab0-ed15-45ad-baa0-caa0e70df9a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu_item_101']</value>
      <webElementGuid>4327e52f-967e-4bb9-87a4-e2a15b499a8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='left_menu_item_10']/a</value>
      <webElementGuid>12f19fcf-c6d5-4e3a-ba0a-3eae4fbf08c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='People Management'])[1]/following::a[1]</value>
      <webElementGuid>0616a157-f25c-4333-a92a-57cb20cd0caf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='search'])[1]/following::a[1]</value>
      <webElementGuid>2729e646-99cf-46e1-ba90-df7880caf735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HR Administration'])[2]/preceding::a[1]</value>
      <webElementGuid>9cfcd565-7823-411d-85e9-cdb2a9d22430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/admin/systemUsers')]</value>
      <webElementGuid>5aeb60a2-7678-473b-a774-531e258d3a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>93dd7acc-2b2a-41e3-899f-852e7f96a2db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/admin/systemUsers' and @id = 'menu_item_101' and (text() = 'path{fill:#64728c;}
HR Administration' or . = 'path{fill:#64728c;}
HR Administration')]</value>
      <webElementGuid>aea863f8-e01e-4be8-adc1-b744902edaa7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
