<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_20</name>
   <tag></tag>
   <elementGuidId>eb8518fe-2259-4d9d-a4d8-3663bfdb5232</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mount-vue-app']/div/div[2]/div/div/div/div/div[4]/nav/ul/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.oxd-select-text.oxd-select-text--focus.pagination-dropdown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^20$/ >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a65b4c59-2a39-4177-a790-c75b274fcd62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-select-text oxd-select-text--focus pagination-dropdown</value>
      <webElementGuid>1811d350-1748-4451-b9f0-7cc5efbed6c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>834107f1-1360-4120-859a-923734c059e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hide-dropdown-default-label</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5a4f6c5f-cb0f-4298-ac13-723a08f96bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>53c72259-377c-4b91-a1af-e8ac59c629a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mount-vue-app&quot;)/div[@class=&quot;vue-container&quot;]/div[@class=&quot;work-schedule-list-container&quot;]/div[@class=&quot;tab-content&quot;]/div[1]/div[@class=&quot;oxd-sheet oxd-sheet--rounded oxd-sheet--white oxd-list-card&quot;]/div[@class=&quot;oxd-list-content&quot;]/div[@class=&quot;oxd-list-content-footer&quot;]/nav[1]/ul[@class=&quot;oxd-pagination__ul&quot;]/div[@class=&quot;oxd-select-wrapper&quot;]/div[@class=&quot;oxd-select-text oxd-select-text--focus pagination-dropdown&quot;]</value>
      <webElementGuid>de01e0f1-8a5d-483e-b95a-180808211af7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mount-vue-app']/div/div[2]/div/div/div/div/div[4]/nav/ul/div/div</value>
      <webElementGuid>5cecee02-fb6c-4afa-bc4c-4a58fc321091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='United States Twilight'])[1]/following::div[7]</value>
      <webElementGuid>36454c08-2273-4ad8-9a44-c57bf532cd0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OrangeHRM 7.12-VAS'])[1]/preceding::div[6]</value>
      <webElementGuid>2a6484e3-9fd2-46aa-a6ff-45754add152f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/div/div</value>
      <webElementGuid>d527a94f-a483-40f3-b20a-552647d0babc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '20' or . = '20')]</value>
      <webElementGuid>df85a7b5-e395-45f3-8242-c207ee36b45b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
