<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Work Schedules</name>
   <tag></tag>
   <elementGuidId>859665d7-03c4-4195-b2fc-6233991d5b26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.tab-items</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mount-vue-app']/div/div[2]/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>li >> internal:has-text=&quot;Work Schedules&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>47c8875b-ef26-46cb-903f-0ae9c3c6edfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab-items</value>
      <webElementGuid>e9864ca7-de1d-4871-b03f-14d02e9f44b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Work Schedules</value>
      <webElementGuid>c038443b-05e2-42b8-9f11-5159d74b1679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mount-vue-app&quot;)/div[@class=&quot;vue-container&quot;]/div[@class=&quot;work-schedule-list-container&quot;]/ul[@class=&quot;tab-list&quot;]/li[@class=&quot;tab-items&quot;]</value>
      <webElementGuid>e6e56ba0-a976-470c-87cd-bbdf2c72eceb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mount-vue-app']/div/div[2]/ul/li</value>
      <webElementGuid>b1fda929-83e6-4877-afd4-d6803c89c4c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Timesheet'])[2]/following::li[1]</value>
      <webElementGuid>c40e2a7c-e1d0-416c-b353-8f33b5b82897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit Request'])[2]/following::li[1]</value>
      <webElementGuid>430f89b4-3e64-4278-aea3-526746bd35f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li</value>
      <webElementGuid>b7633186-1814-4638-a09c-2117e1066763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Work Schedules' or . = 'Work Schedules')]</value>
      <webElementGuid>c660b05b-a719-4b68-aace-55dbb8b852aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
