<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test Suite - Edit work schedule</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>3c599661-ac88-461d-96f0-05543dba3a35</testSuiteGuid>
   <testCaseLink>
      <guid>372d6196-b449-4799-8200-9caf0a775eee</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MAP9-155_Edit work schedule RecordWeb/MAP9-176_TC1 - Edit existing work schedule</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cae0e1f7-a134-4e9f-9163-8e976215bf74</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>438eea1c-e8b5-4f63-b5cd-dd871f5a7fc5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>24c81df0-1b95-4b13-851d-850f0cdff69d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MAP9-155_Edit work schedule RecordWeb/MAP9-177_TC2 - Invalid break hrs</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>7cf842a3-1abd-412f-ad49-81ca23d34ab4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MAP9-155_Edit work schedule RecordWeb/MAP9-178_TC3 - Changes not saved</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43c456b4-d660-45e3-98bf-7abed4253a4c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50239a9f-631b-4a7a-a200-976daf671066</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
