<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Job oxd_menu_down</name>
   <tag></tag>
   <elementGuidId>28af7ad7-543d-40c3-b344-79f813ce4245</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#top_level_menu_item_menu_item_102 > a.top-level-menu-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='top_level_menu_item_menu_item_102']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Job oxd_menu_down&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c01c9c5d-f91f-401e-b0b4-1d2ea6efea51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!sref &amp;&amp; !menuTooltip</value>
      <webElementGuid>a68a53ec-11fe-4cb2-9065-8dac23d26ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-href</name>
      <type>Main</type>
      <value>{{href}}</value>
      <webElementGuid>ee3e0e38-2da0-46ee-89f7-dfbc7900d50c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>top-level-menu-item </value>
      <webElementGuid>588b3e77-0d68-4f40-9d1a-ae953b2ee56e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-target</name>
      <type>Main</type>
      <value>{{target}}</value>
      <webElementGuid>002ce97b-0498-4150-b8c1-9837a029d334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>toggleShowSubmenu()</value>
      <webElementGuid>56ce3c90-6bd6-4368-a84a-61c11e519595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>menu_admin_Job</value>
      <webElementGuid>7fdf4fe0-66bb-46b4-9520-03e7fb49a041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3d60056a-3e02-40e5-8beb-12808ee6809c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Job oxd_menu_down </value>
      <webElementGuid>780a994a-fbe8-4ae5-860f-3c82cf0035a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top_level_menu_item_menu_item_102&quot;)/a[@class=&quot;top-level-menu-item&quot;]</value>
      <webElementGuid>ab193dc3-bd09-48ba-a69d-33321cb7563a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top_level_menu_item_menu_item_102']/a</value>
      <webElementGuid>eb1e0560-4c83-4766-b0d3-54b7c174ddcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage User Roles'])[1]/following::a[1]</value>
      <webElementGuid>cbece9b6-25c7-4d5f-9cc1-0dd96b506447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Users'])[1]/following::a[2]</value>
      <webElementGuid>ef37b489-23f7-430a-90f1-81260e3fa230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Salary Components'])[1]/preceding::a[1]</value>
      <webElementGuid>d1db4397-411a-48b2-96b3-943f65752e77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Job']/parent::*</value>
      <webElementGuid>cd5f0855-b996-41be-be15-c571e6e3c460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//top-level-menu-item[3]/div/a</value>
      <webElementGuid>9b45a3f6-d44b-4533-a601-fee09a687b85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Job oxd_menu_down ' or . = 'Job oxd_menu_down ')]</value>
      <webElementGuid>a28c209e-6ebc-437d-a220-bf03e9729d68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
