<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_My Timesheet_systemUserDiv</name>
   <tag></tag>
   <elementGuidId>d530d5e9-89fa-4da2-adfa-dcfe02ec2e51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#systemUserDiv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='systemUserDiv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#systemUserDiv</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>35b8f448-e6fb-4652-9634-ab8bdc8b9df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>systemUserDiv</value>
      <webElementGuid>b452885f-bf44-4e18-9ef9-08cf99d45ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;systemUserDiv&quot;)</value>
      <webElementGuid>1ff051f5-2c07-4004-b0e4-bb09bc49ff66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='systemUserDiv']</value>
      <webElementGuid>dba523d0-fea4-450a-b8ef-88a333cf2ceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mount-vue-app']/ui-view/div/div</value>
      <webElementGuid>a4fc2306-8604-4f16-a5bc-7f6839460419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Timesheet'])[2]/following::div[7]</value>
      <webElementGuid>a4507f39-fb50-481c-8908-4a006eb82ef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit Request'])[2]/following::div[10]</value>
      <webElementGuid>e96854ea-c0d2-4719-a59b-3dcc25c8e94b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OrangeHRM 7.12-VAS'])[1]/preceding::div[2]</value>
      <webElementGuid>0c979888-ef6d-43c9-9c61-c3a424bfdf6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ui-view/div/div</value>
      <webElementGuid>03b742ed-235c-487d-a612-9ae5e459a716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'systemUserDiv']</value>
      <webElementGuid>940a83a3-d2b0-4476-949a-ccb874592308</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
